### ISSUE TITLE
k8s jobs need to record accurate cpu/vm usage 

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-workflows#189]
Bespin jobs that run in openstack keep track of their cpu/vm usage.
K8s bespin jobs use varying amounts of cpu/VMs so changes will be needed to accurately represent cloud utilization.

**Comment by dleehr** [comment]
https://github.com/Duke-GCB/calrissian/pull/51 implemented a feature to record calrissian's usage reports in a JSON file. This will count the usage of individual step containers inside a workflow, but will not include the time to stage the data in/out or the time to orchestrate those workflow containers.

**Comment by dleehr** [comment]
Some background on how we compute this data

- Openstack job CPU usage time is a simple calculation done inside of bespin-api. We determine the job's runtime based on start and finish times in the model, then multiply that by the number of CPUs in the flavor.
- Openstack VM strategy is simple because all of the work to run a job happens during the life of that VM (Staging in, compute, staging out)
- On k8s however, there are multiple layers and submitted jobs, so we can't apply the same simple calculation.

**Comment by dleehr** [comment]
See https://github.com/Duke-GCB/bespin-api/blob/master/data/jobusage.py - the openstack vm case is a little more complicated (considering start/cancel/idle times) but still a linear calculation.

**Comment by dleehr** [comment]
JobActivity objects get created by Jobs when state changes, so that has timelines for when staging operations happen (since these are state changes in the job). So let's work on enhancing JobActivity to account for CPU and memory usage.

There's no web API for creating a job activity - they're generated by changing the job state, and the assumption that all activities on a job use the same resources per amount of time feeds into the simple calculation.

So we could

1. adjust JobActivity to include CPU/memory usage. This can track with the k8s jobs submitted by lando to stage data.
2. Inside of lando, calculate the total CPU/memory usage of the workflow running step (adding the calrissian job with the pods it submits and reports). Since these would be of different sizes and shapes, lando would need to submit this record to bespin-api somehow.

**Comment by dleehr** [comment]
On further discussion, towards getting to live reporting, I'd like to try having a tree of JobActivity objects, where a high-level activity (such as running workflow) can have a stream of child activities (running fastqc, running bwa, running markduplicatses that contribute to their total usage for an accurate summary with detailed reports.

**Comment by johnbradley** [comment]
Created issue for lando to save report: https://github.com/Duke-GCB/lando/issues/166

**Comment by dleehr** [comment]
Example from calrissian 0.3.0 attached.

Excerpt from job yaml:

```
      - name: calrissian
        image: dukegcb/calrissian:0.3.0
        command: ["calrissian"]
        args:
          - "--pod-labels"
          - "/calrissian/input-data/labels.yaml"
          - "--default-container"
          - "debian:stretch-slim"
          - "--max-ram"
          - "64G"
          - "--max-cores"
          - "32"
          - "--tmpdir-prefix"
          - "/calrissian/tmptmp/"
          - "--tmp-outdir-prefix"
          - "/calrissian/tmpout/"
          - "--outdir"
          - "/calrissian/output-data/"
          - "--usage-report"
          - "/calrissian/output-data/exomeseq-gatk4-usage-report.json"
          - "/calrissian/input-data/workflow/exomeseq-gatk4-preprocessing.cwl"
          - "/calrissian/input-data/job/gatk4-preprocessing.json"
```

https://gist.github.com/dleehr/83136be140f64b8af4b66012c2bf5a19
